NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GCADAZ22Y6EUC575N4SRMGYVXTODH5MOHM3EVHQNC7AZ6PTZNJI7SXRP"
]

[[CURRENCIES]]
code="XEVA"
issuer="GCADAZ22Y6EUC575N4SRMGYVXTODH5MOHM3EVHQNC7AZ6PTZNJI7SXRP"
display_decimals=7
name="XEVA"
desc="A community-led Stellar asset for fast, borderless value."
image="https://xeva-project.vercel.app/xeva-logo.svg"
status="live"
fixed_number=922337203685
